#version 450
layout(local_size_x = 16, local_size_y = 16) in;
layout(set = 0, binding = 0, rgba8) uniform writeonly image2D outputImage;

void main() {
    ivec2 pos = ivec2(gl_GlobalInvocationID.xy);
    ivec2 size = imageSize(outputImage);
    
    if(pos.x < size.x && pos.y < size.y) {
        // Green color to distinguish from RenderPass clear (Red)
        imageStore(outputImage, pos, vec4(0.0, 1.0, 0.0, 1.0)); 
    }
}
